name: Docker Build, Push, and Deploy House Price Predictor model server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/house-price-predictor:latest

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /home/ubuntu/plf
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/house-price-predictor:latest
          docker stop house-predictor || true
          docker rm house-predictor || true
          docker run -d --name house-predictor -p 5959:8000 -v $(pwd):/app ${{ secrets.DOCKER_HUB_USERNAME }}/house-price-predictor:latest
